apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes within the cluster
      targetPort: 80 # The port the container is listening on
      nodePort: 30080 # The static port exposed on the host node (Minikube)
